# Site settings
title: Gabriel Rosa Cencic
email: gabriel.cencic@gmail.com
url: https://github.com/gcadeado/portfolio
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "gabriel, rosa, cencic, portfolio, developer, game"
skills: "Game Developer"
meta_author: Cencic Gabriel

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact:

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 80B3FF
  primary-rgb: "128,179,255"
  secondary: FD6E8A
  secondary-dark: A2122F

# Footer settings
footer:
  copyright: Synaesthetic Studios
  location: Location
  social: Surfing the Webz
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/gcadeado
  - title: linkedin
    url: https://www.linkedin.com/in/gabrielcencic/
  - title: medium
    url: https://medium.com/@gabrielcencic

# Postal address (add as many lines as necessary)
address:
  - line: Berlin, DE
  - line:

# Credits content
credits: 'Freelancer theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
